# Syllabus {.unnumbered}

[{{< bi download >}}](CivProSyllabus.pdf "Download Syllabus")

::: {.syllabus}

::: {.syllabus-header}

## {{< var subject >}} {.unnumbered}

{{< var institution >}}

{{< var term >}}

{{< var room >}}

{{< var meets >}}

[{{< var repo-name >}}]({{< var repo-url >}})

### Professor

{{< var author >}}

{{< var phone >}}

[{{< var email >}}](mailto:{{< var email >}})

Office hours: [[calendly.com/emfink]({{< var appointments >}})]{.mono-font-smaller}

### Teaching Assistants {.unnumbered}

{{< var ta >}}

[{{< var ta-email >}}](mailto:{{< var ta-email >}})

:::

## Description {.unnumbered}

In this course, you will learn about the procedures for civil suits. Topics to be covered include the scope of a lawsuit, selection of an appropriate forum, presentation of claims and defenses, choice of applicable law, disposition without a trial, and the effect of judgments on future litigation. Other aspects of civil litigation (e.g., discovery, trials, & appeals) are covered in upper-level elective courses. While the course will focus on federal courts, the rules of civil procedure in many states (including North Carolina) are similar.

This course is intended to prepare you for legal practice by developing the knowledge and skill required to recognize and analyze procedural issues in civil litigation, advise clients on those issues and the available options, and draft pleadings and motions.

## Course Materials {.unnumbered}

### Required

Civil Procedure: An Open-Source Casebook (v.5.0 2026). Available on the course website: [[emfink.net/CivPro](https://www.emfink.net/CivPro/)]{.mono-font}.

[Click & Learn Civil Procedure](https://clickandlearnguide.com) (Carolina Academic Press). Class Code: 326-138-9849. 

### Suggested

Kevin M. Clermont, _Principles of Civil Procedure_ (West Academic 7th ed. 2024). Digital version available at no cost through the [West Academic Online Study Aids Collection](https://subscription.westacademic.com/). This hornbook provides concise overviews of the topics covered in the course. 

Joseph W. Glannon, _Examples & Explanations for Civil Procedure_ (Aspen 9th ed.) or _The Glannon Guide to Civil Procedure_ (Aspen 5th ed.). These are two popular study aids for Civil Procedure, presenting similar content in different formats. 

## Policies {.unnumbered}

### Grading

Your final grade for the term will be based on the assigned Click & Learn lessons (20%) and a final exam (80%):

- The Click & Learn assignments are intended to help you review & assess your understanding of the topics covered. The Schedule & Assignments section below lists the corresponding Click & Learn unit for each part of the course. Required lessons in each unit are indicated by a due date of December 1.[^syllabus1] You may work on the Click & Learn lessons at your own pace and may redo them as many times as you like, as long as you complete them all by December 1. Your grade will be based on your highest score for each lesson. 
- The final exam (closed-book/closed-note) will consist of essay and short-answer questions. You will take the final exam at the Law School during the Fall Term exam period (date & time TBA). Sample questions from past exams are posted on the [course website](https://www.emfink.net/CivPro/). 

[^syllabus1]: Click & Learn lessons without a due date are not required and will not count toward your final grade.

### Attendance

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
> 
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student’s instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

### Disability Accommodations

For disability accommodation requests, contact the [Elon Disability Services Office](https://www.elon.edu/u/academics/koenigsberger-learning-center/disabilities-resources/homepage/graduate-student-resources/).

### Honor Code

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including conduct during class and examinations.

## Schedule & Assignments {.unnumbered}

_Note:_ This class will not meet on Sept. 7, Sept.21, and Oct. 16. 

### 1\. Foundations of Civil Procedure

_Clermont_ chap. 1 & 2[^syllabus3] 

_Click & Learn_ Basic Skills & Fundamentals

#### Monday, August 31

- At the Threshold; Civil Litigation in Federal Court, _Casebook_ §§ 1.1 & 1.2

### 2\. Parties and Claims

_Clermont_ chap. 6 

_Click & Learn_ Unit 6 (parts 1, 2, & 3)

#### Wednesday, September 2 

- Permissive Joinder of Claims & Parties, _Casebook_ §§ 2.1 & 2.2 

#### Friday, September 4 

- Counterclaims, _Casebook_ § 2.3 

#### Wednesday, September 9 

- Crossclaims, _Casebook_ § 2.4 

#### Friday, September 11

- Third-Party Defendants & Claims, _Casebook_ § 2.5 

####  Monday, September 14 

- Required Parties, _Casebook_ chap. 2: § 2.6 

#### Wednesday, September 16 

- Joinder Wrap-Up

### 3\. Personal Jurisdiction

_Clermont_ chap. 4: §§ 4.2-4.4 

_Click & Learn_ Unit 1 (parts 1-7)

#### Friday, September 18 & Wednesday, September 23

- Constitutional Limits: Due Process, _Casebook_ § 3.1 

#### Friday, September 25 & Monday, September 28

- Specific Jurisdiction, _Casebook_ § 3.1 

#### Wednesday, September 30

- General Jurisdiction, _Casebook_ § 3.3

#### Friday, October 2

- Consent; Long-Arm Statutes, _Casebook_ §§ 3.4 & 3.5

### 4\. Subject Matter Jurisdiction

_Clermont_ chap. 4: § 4.1 

_Click & Learn_ Unit 3 (parts 1-4 & 6)

#### Monday, October 5 & Wednesday, October 7

- Federal Question Jurisdiction, _Casebook_ § 4.1 

#### Friday, October 9 & Monday, October 12 

- Diversity Jurisdiction, _Casebook_ § 4.2 

#### Wednesday, October 14 & Monday, October 19

- Supplemental Jurisdiction, _Casebook_ §§ 4.3

### 5\. Choice of Governing Law

_Clermont_ chap. 3 

_Click & Learn_ Unit 9 

#### Wednesday, October 21 & Friday, October 23

- Rules of Decision Act & Erie, _Casebook_ § 5.1 

#### Monday, October 26 & Wednesday, October 28

- Rules Enabling Act & Hanna, _Casebook_ § 5.2 & 5.3 

### 6\. Pleading

_Clermont_ chap. 2: § 2.2(A) 

_Click & Learn_ Unit 5 (parts 1-3, & 5)

#### Friday, October 30

- Pleading Under the Federal Rules, _Casebook_ §§ 6.1

#### Monday, November 2 & Wednesday, November 4

- Assessing the Sufficiency of a Claim, _Casebook_ §§ 6.2

#### Friday, November 6

- Answers & Defenses _Casebook_ § 6.3

#### Monday, November 9

- Truthfulness and Good Faith, _Casebook_ § 6.4

### 7\. Effect of Judgments

_Clermont_ chap. 5 

_Click & Learn_ Unit 10 (part 1 only)

#### Wednesday, November 11 & Friday, November 13

- Full Faith & Credit; Claim Preclusion, _Casebook_ §§ 7.1 & 7.2

#### Monday, November 16 & Wednesday, November 18

- Issue Preclusion, _Casebook_ § 7.3 

### 8\. Summary Judgment

_Clermont_ chap. 2: § 2.2 

_Click & Learn_ Unit 8 (part 1 sec. III only) 

#### Friday, November 20

- Judgment as a Matter of Law; Genuine Issue of Material Fact, _Casebook_ §§ 8.1 & 8.2 

---

**Date TBA** Final Review

**Date TBA** Final Exam

[^syllabus3]: Relevant portions of the Clermont hornbook are listed for each unit. These are optional, but you may find them helpful to provide context for the assigned reading.

:::