# Sources {.unnumbered}

## Cases

_Buck v. Gordon_, 959 F. 3d 219 (6th Cir. 2020)

_Burdine v. Metropolitan Direct Property and Casualty Ins. Co._, 3:17-cv-00093-GFVT (E.D. Ky. November 1, 2018)

_Byrd v. Blue Ridge Rural Elec. Cooperative, Inc._, 356 U.S. 525 (1958)

_Camacho v. Major League Baseball_, Case No. 12-cv-2859-L(BGS) (S.D. Cal. December 19, 2013)

_Carnival Cruise Lines_, Inc. v. Shute, 499 U.S. 585 (1991)

_Complete Business Solutions Group, Inc. v. Annie’s Pooch Pops_, No. 20-724 (E.D. Pa. July 18, 2020)

_Crane v. City of Arlington_, Texas, 50 F. 4th 453 (5th Cir. 2022)

_Daimler Ag v. Bauman_, 571 U.S. 117 (2014)

_Doe v. Clinton County_, 1:25-cv-368 (W.D. Mich. April 28, 2025)

_Dolphin Kickboxing Co. v. Franchoice, Inc._, Case No. 19-cv-1477 (MJD/ECW) (D. Minn. May 6, 2020)

_Elden v. Nirvana, L.L.C._, Case No. CV 21-6836 FMO (AGRx) (C.D.Cal. Sept. 30, 2025)

_Erie R. Co. v. Tompkins_, 304 U.S. 64 (1938)

_Exxon Mobil Corp. v. Allapattah Services, Inc._, 545 U.S. 546 (2005)

_Ford Motor Co. v. Montana Eighth Judicial Dist. Court_, 592 U.S. 351 (2021)

_Ginwright v. Exeter Finance Corp._, 280 F. Supp. 3d 674 (D. Md. 2017)

_Grable & Sons Metal Products, Inc. v. Darue Engineering & Mfg._, 545 U.S. 308 (2005)

_Hanks v Coan_, 1:99CV00119 (M.D.N.C. August 17, 1999)

_Hanna v. Plumer_, 380 U.S. 460 (1967)

_Hernandez v. Asset Acceptance_, LLC, 970 F. Supp. 2d 1194 (D. Colorado 2013)

_Hunter v. Earthgrains Co. Bakery_, 281 F. 3d 144 (4th Circuit 2001)

_In re Nageleisen_, 523 BR 522 (E.D. Kentucky, Bankr. 2014)

_International Shoe Co. v. Washington_, 326 U.S. 310 (1945)

_Janjua v. Neufeld_, 933 F. 3d 1061 (9th Circuit 2019)

_Johnson v. Cricket Council USA, Inc._, 658 F. Supp. 3d 276 (E.D.N.C. 2023)

_Johnson v. Griffin_, 85 F. 4th 429 (6th Circuit 2023)

_Johnson v. Spencer_, 950 F. 3d 680 (10th Circuit 2020)

_Jones v. Ford Motor Credit Co._, 358 F. 3d 205 (2nd Cir. 2004)

_Kirkcaldy v. Richmond County Bd. of Ed_, 212 F.R.D. 289 (M.D.N.C. 2002)

_Lee v. POW! Entertainment, Inc._, 468 F. Supp. 3d 1220 (C.D. Cal. 2020)

_Lehman v. Revolution Portfolio LLC_, 166 F. 3d 389 (1st Cir. 1999)

_Louisville & Nashville R. Co. v. Mottley_, 211 U.S. 149 (1908)

_Mallory v. Norfolk Southern Ry. Co._, 600 U.S. 122 (2023)

_McGee v. International Life Ins. Co._, 355 U.S. 220 (1957)

_Mine Workers v. Gibbs_, 383 U.S. 715 (1966)

_Moore v. Baker_, 989 F. 2d 1129 (11th Circuit 1993)

_Mosley v. General Motors Corp._, 497 F. Supp. 583 (E.D. Missouri 1980)

_National Satellite Sports, Inc. v. Eliadis, Inc._, 253 F. 3d 900 (6th Circuit 2001)

_NBA Properties, Inc. v. HANWJH_, 46 F. 4th 614 (7th Circuit 2022)

_Ottawa Township Board of Trustees v. New Par (I)_, Case No. 3:17CV228 (N.D. Ohio July 10, 2017)

_Ottawa Township Board of Trustees v. New Par (II)_, Case No. 3:17CV228 (N.D. Ohio October 10, 2017)

_Pace v. Timmermann’s Ranch and Saddle Shop Inc._, 795 F. 3d 748 (7th Cir. 2014)

_Palacio v. City of Springfield_, 25 F. Supp. 3d 163 (D. Mass. 2014)

_Parklane Hosiery Co. v. Shore_, 439 U.S. 322 (1978)

_Passaro v. Virginia_, 935 F. 3d 243 (4th Circuit 2019)

_Pennoyer v. Neff_, 95 U.S. 714 (1878)

_Reis Robotics USA, Inc. v. Concept Industries_, 462 F. Supp. 2d 897 (N.D. Ill. 2006)

_Shiftlet v. Allstate Insurance Co._, 451 F. Supp. 2d 763 (D.S.C. 2006)

_Smith v. Safemarine Corp._, 749 F. Supp. 3d 687 (M.D. Louisiana 2024)

_Stout v. Vincent_, 717 Fed. Appx. 468 (5th Cir. 2018)

_Sullivan-Blake v. Fedex Ground Package System, Inc_., Civil Action No. 18-1698 (W.D. Pa. January 31, 2020)

_Swift v. Tyson_, 41 U.S. 1 (1842)

_Taylor v. Sturgell_, 553 U.S. 880 (2008)

_Turton v. Virginia Department of Education_, Civil Action No. 3:14cv446 (E.D. Va. January 15, 2015)

_Williams v. Mitchell_, 122 F. 4th 85 (4th Circuit 2024)

_Williams v. The Estates LLC_, 663 F. Supp. 3d 466 (M.D.N.C. 2023)

_World-Wide Volkswagen Corp. v. Woodson_, 444 U.S. 286 (1979)

_Zielinski v. Philadelphia Piers_, 139 F. Supp. 408 (Dist. Court A. No. 15153)

## Books, Articles, & Other Publications

Administrative Office of the U.S. Courts, [_Understanding the Federal Courts_](https://www.uscourts.gov/sites/default/files/understanding-federal-courts.pdf), (n.d.)

Matthew Butterick, [_Typography for Lawyers 2nd_](https://typographyforlawyers.com) (2015)

William R Casto, _The Erie Doctrine and the Structure of Constitutional Revolutions_, 62 Tulane Law Review 907 (1987)

Charles Dickens, [[Bleak House]{.small-caps-text}](https://standardebooks.org/ebooks/charles-dickens/bleak-house) (1853)

William Felstiner, Richard Abel & Austin Sarat, _The Emergence and Transformation of Disputes: Naming, Blaming, Claiming…_, 15 Law & Society Review 631 (1980)

Brian L Frye, _The Ballad of Harry James Tompkins_, 52 Akron Law Review 531 (2018)

Oliver Wendell Holmes, [The Common Law]{.small-caps-text} (1881)

E. Polk Johnson, [[A History of Kentucky and Kentuckians: The Leaders and Representative Men in Commerce, Industry and Modern Activities]{.small-caps-text}](https://play.google.com/books/reader?id=FXQUAAAAYAAJ&pg=GBS.PA1144.w.2.1.0_421) (1912), 

Franz Kafka, [_Before the Law_](https://www.kafka-online.info/before-the-law.html), (1915) 

Thomas S. Kuhn & Ian Hacking, [The Structure of Scientific Revolutions: 50th Anniversary Edition]{.small-caps-text} (2012)

David Marcus, _The Federal Rules of Civil Procedure and Legal Realism as a Jurisprudence of Law Reform_, 44 Georgia Law Review 433 (2009)

Jack Metzler, _Cleaning Up Quotations_, 18 The Journal of Appellate Practice and Process 143 (2017)

Wendy Perdue, _Sin, Scandal, and Substantive Due Process: Personal Jurisdiction and Pennoyer Reconsidered_, 62 Washington Law Review 479 (1987)

George Rutherglen, _International Shoe and the Legacy of Legal Realism_, 2001 The Supreme Court Review 347 (2001)

Logan Everett Sawyer III, _Jurisdiction, Jurisprudence, and Legal Change: Sociological Jurisprudence and the Road to International Shoe_, 10 George Mason Law Review 59 (2001)

