---
date: Fall 2022

title: Civil Procedure
subtitle: "Quiz 1: Personal Jurisdiction"

author: Eric M. Fink
affiliation: Elon Law School 

exam: true 
    
---

## Instructions

- This is an open-book/open-notes quiz. You may use any printed material, but may not use computers, phones, or other electronic devices. You have 45 minutes to complete the quiz 
- When you are done, return your answer sheet and the questions to the proctor. 
- Include your Midterm Exam ID number, *not your name*, on your answer sheet. 
- For each question, assume that any applicable long-arm statute authorizes jurisdiction to the full extent permitted under the U.S. Constitution. 


### Question 1

Peter lives in Pennsylvania, where he also has a business called "Peter's Produce". In search of new items to sell, Peter travels to New Mexico to sample the local peppers. During his trip, Peter visits Pepe's Pepper Paradise, which makes artisinal pickled peppers from New Mexico Pueblo chiles. Predicting that pickled Pueblo peppers would prove popular with his patrons in Pennsylvania, Peter proposes to Pepe that they enter into a business partnership, promising profuse profits. Pepe declines, explaining that he only sells the peppers locally and isn't interested in expending his business. Peter purchases two pecks of pickled peppers, telling Pepe he plans to sell them in his store in Pennsylvania. 

After returning home, Peter sells a jar of Pepe's pickled peppers to one of his customers. Shortly after eating the peppers, the customer becomes violently ill and is diagnosed with botulism, a severe and potentially fatal type of food poisoning. The customer asks Peter where the peppers came from, and Peter explains he bought them from Pepe in New Mexico. The customer files a suit against Pepe in a Pennsylvania court, alleging that the botulism resulted from Pepe's failure to sterilize the pepper jars properly. Is personal jurisdiction over Pepe in Pennsylvania proper? 

a. Yes, because the customer bought the peppers in Pennsylvania. 

b. Yes, because Peter told Pepe he was going to sell the peppers in Pennsylvania. 

c. No, because Pepe doesn't live in Pennsylvania. 

d. No, because Pepe wasn't responsible for the sale of the peppers in Pennsylvania. 

### Question 2

During his trip to New Mexico, Peter also met Carmen, a local chef renowned for her Calabacitas (a traditional dish made from sauteed roasted green chile, summer squash, and corn). Carmen has been canning and selling her Calabacitas locally, and is interested in expanding her market. Peter and Carmen enter into a contract under which Carmen will ship cases of canned Calabacitas from her production facility in New Mexico to Peter in Pennsylvania, and Peter will distribute them to retailers in Pennsylvania, New Jersey, Maryland, and Delaware. The contract provides that Peter pay for advertising in local newspapers in those four states to promote interest in the product. Peter will keep 25% of the revenue from sales he generates and remit the balance to Carmen in New Mexico.  

Peter sells a case of Carmen's Calabacitas to Dan's Delicacies, a retail shop in Rehoboth Beach, Delaware. Sam a New York resident who is on vacation in Rehoboth, samples some of Carmen's Calabacitas at Dan's Delicacies and finds them so delicious he buys several cans to take back to New York. When Sam arrives home, he opens one of the cans and cuts himself on a sharp edge, badly injuring his hand. If Sam wishes to bring a lawsuit for his injury, in which state(s) would a court have personal jurisdiction over Carmen? 

a. New Mexico only.  

b. New Mexico and Pennsylvania. 

c. New Mexico, Pennsylvania, and Delaware. 

d. New Mexico and New York. 


### Question 3

Daisy Duke, a Philadelphia resident, broke her tooth on a foreign object in some store-brand canned luncheon meat (a.k.a. generic "Spam") she purchased at her local Colossus Foods grocery store. She met with a lawyer about bringing a suit to recover damages for the expensive dental work she required, as well as the emotional distress she suffered from the traumatic experience. After some investigation, the lawyer learned that Colossus Foods (based in Maryland and operating retail stores in both Maryland and Pennsylvania) buys its store-brand products from a wholesale distributor called Zysco, based in Indiana. Zysco in turn contracts with various manufacturers, including Harmer Meats (based in Arizona), which made the generic Spam that caused Duke's injury. The contract between Harmer and Zysco authorizes Zysco to distribute Harmer's products in 35 states, including Pennsylvaia. The contract also provides that Harmer will submit samples of its products to the Pennsylvania State Department of Agriculture for testing, as Pennsylvania law requires for all packaged foods sold in the state. 

Duke's lawyer files a suit against Colossus, Zysco, and Harmer in Pennsylvania state court. Which of the defendants are within the court's personal jurisdiction? 

a. Only Collosus.

b. Collosus and Zysco, but not Harmer.

c. Collosus and Zysco, and Harmer.

d. None of the above. 

### Question 4

Neff, a resident of California, hires Mitchell, an Oregon lawyer, to represent Neff in the acquisition of some land in Oregon. Neff has never actually been to Oregon, and his dealings with Mitchell took place by mail and telephone. After the transaction is completed, Neff refuses to pay Mitchell's fee. Mitchell sues Neff for breach of contract in an Oregon court. After filing the suit, Mitchell has a copy of the complaint and summons served on Neff in a manner authorized by the Federal Rules of Civil Procedure. Neff ignores the summons, neither responding to the complaint nor appearing in court on the appointed day. The court enters a default judgment in favor of Mitchell. Is the default judgment against Neff valid? 

a. No, unless Mitchell has the Oregon court attach Neff's Oregon property at the outset of the suit. 
b. No, because Neff lives outside Oregon and has never been to the state. 
c. Yes, because Mitchell's suit arose out of Neff's hiring Mitchell, an Oregon attorney, to represent Neff in the acquisition of Oregon property and Neff's subsequent failure to pay Mitchell's fee. 
d. Yes, because Neff failed to appear for the purpose of objecting to the Oregon court's jurisdiction. 

### Question 5

Tiger Foods (based in North Carolina) is a supermarket chain with stores located in North Carolina & Virginia. US Broadcasting Corp. ("UBC", based in New York), produces television programs that air nationally, in some places on local TV stations owned by UBC, in other places on independent stations that contract with UBC for programming. Linda Lewis (a resident of Virginia) is a reporter employed by UBC. 

For a program on unsavory practices in the retail food industry, UBC assigned Lewis to go undercover at Tiger Foods. Lewis got hired as a deli counter clerk at a Tiger Foods store in Virginia and secretly videotaped activity there. Among other things, she recorded store managers instructing employees to re-label past-date foods (including spoiled meats and dairy products) and return them to sale displays. 

Kari Kaplan, a UBC employee at the company's New York headquarters, produced the program. Kaplan included parts of Lewis's video footage, with a voice-over stating that the practice of re-labeling and selling past-date and spoiled foods "violates state and federal laws". Kaplan also contacted Steve Shill, Director of Public Relations for Tiger Foods, by email and telephone at his office in North Carolina, inviting him to comment on behalf of the company. Parts of Shill's comments were included in the program. 

After the program airs, sales at Tiger Foods stores fall by 25%. Tiger Foods sues UBC for defamation, alleging that the undercover video footage and Shill's comments were deceptively edited or presented out of context, and that none of the company's stores ever sold past-date or spoiled foods in violation of any state or federal laws. Tiger Foods files its suit in a North Carolina court. Does the court have personal jurisdiction over UBC?

a. Yes, but only if the program aired in North Carolina on a station owned by UBC. 

b. Yes, even if the stations that aired the program in North Carolina were not owned by UBC. 

c. No, because neither Lewis nor Kaplan ever went to North Carolina in connection with the program.  

d. No, unless Lewis or Kaplan owns property in North Carolina. 