---

date: Fall 2019

title: Civil Procedure
subtitle: "Quiz: Subject Matter Jurisdiction & Choice of Law"

author: Eric M. Fink
affiliation: Elon Law School 

exam: true
nofoot: true
geometry: top=1in,bottom=.75in,left=1in,right=1in

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.tex
    
---

# Answers & Explanations 

1. In which of the following cases would a federal court have diversity jurisdiction under 28 U.S.C. ยง 1332 (assuming all claims arise under state law)? 
	a. Abel (VA) sues Baker (NC), Charlie (TN), Davis (VA), and Edwards (SC), for breach of contract arising out of a real estate deal among the five parties. Under the applicable state law and the contract terms, the defendants are jointly and severally liable for the alleged breach. Abel seeks $80,000 in damages. 
	b. Betty (NC) sues Dupree (VA) seeking $50,000 in damages for fraud, alleging that a diamond ring Dupree sold her was really made of glass. In the same action, Betty also asserts an unrelated negligence claim against Dupree, seeking $50,000 for property damage and personal injuries she sustained when a drunken Dupree crashed into Betty's car. 
	c. Neff (CA) is in possession of a painting valued at $75,000. Pennoyer (OR) sues Neff, to recover the painting, which he claims Neff borrowed but failed to return as promised. 
	d. None of the above.  

The correct answer is B. Betty and Dupree are citizens of different states and the total amount in controversy is $100,000; it doesn't matter that the two claims are unrelated. 

Answer A is incorrect, because the plaintiff (Abel) and one of the defendants (Davis) are both citizens of VA. The amount in controversy requirement is satisfied, because (under joint & several liability) each defendant is potentially liable to Abel for the full $80,000. But without complete diversity, there is no jurisdiction under ยง 1332. 

Answer C is incorrect, because the amount in controversy must _exceed_ $75,000. 

2. Perry (NC) has a homeowner's insurance policy from Dependable Ins. Co. (DE), which he bought through a local agent, Delilah (NC). Perry submits a claim for coverage after a broken water main under his front yard results in property damage costing $50,000 to repair. Dependable denies the claim, asserting that the policy does not cover "flood damage". Perry sues Dependable for breach of contract & bad faith denial of an insurance claim under state law. He seeks $50,000 in compensatory damages and another $50,000 in punitive damages. If Perry files in DE state court, may the defendants remove to federal court? 
	a. Yes, provided state law would allow recovery of punitive damages. 
	b. Yes, if Dependable raises a defense based on federal law. 
	c. No, because Delilah, the Dependable agent who sold the policy, is a NC. 
	d. No, because it's uncertain whether Perry will recover punitive damages. 

The correct answer is A. There is complete diversity between Perry (NC) and Dependable (DE). If state law allows recovery of punitive damages, then the amount in controversy is $100,000; if not, it is only $50,000. 

B is incorrect, because federal question jurisdiction must be based on the plaintiff's claim(s), not defenses. 

C is incorrect, because Deliliah is not named as a party, so her citizenship is irrelevant. Rule 19, which requires joinder of certain persons if feasible, would not apply in this case (for reasons you don't need to worry about). 

D is incorrect, because all that matters is whether Perry has a legally viable claim for more than $75,000. 

3. While Goldilocks (NC) is visiting her Grandmother (VA), Wolf (NC) breaks into Grandmother's house and devours her. Goldilocks manages to escape before Wolf has her for dessert. Goldilocks is named executor of Grandmother's estate. In her representative capacity as executor, Goldilocks brings a wrongful death action in federal court against Wolf on behalf of Grandmother's estate, seeking $100,000 in damages. In the same suit, Goldilocks also asserts her own emotional distress claim against Wolf, seeking $25,000 in damages. Which of the following is correct?  
	a. The court has have diversity jurisdiction over both claims. 
	b. The court has diversity jurisdiction over the wrongful death claim and supplemental jurisdiction over the emotional distress claim. 
	c. The court has diversity jurisdiction over the wrongful death claim, but must remand the emotional distress claim to state court. 
	d. The court must dismiss both claims for lack of subject matter jurisdiction. 

The correct answer is D. 

Looking only at the representative claim on behalf of the estate, the court would have diversity jurisdiction: In her capacity as representative, Goldilocks takes the citizenship of the estate (i.e. Grandmother), which is VA, while the Wolf is a citizen of NC, and the amount in controversy on that claim exceeds $75,000. 

Looking only at the emotional distress claim, Goldilocks's citizenship is based on her own domicile, NC. Since the Wolf is also a citizen of NC, the court would not have diversity jurisdiction over that claim. 

When Goldilocks's emotional distress claim is included with the estate's wrongful death claim, the common citizenship of Goldilocks and the Wolf destroys diversity for the estate's claim as well. Consequently, A, B, & C are all incorrect. 

If Goldilocks and the Wolf were citizens of different states, this problem would be similar to the Star Kist case. The court would have diversity jurisdiction over the estate's claim (because there would be complete diversity), and the court could then exercise supplemental jurisdiction over the emotional distress claim (even though the amount in controversy is not sufficient to give the court diversity jurisdiction over that claim). 

C is incorrect, because this case was originally filed in federal court. Remand is only possible where a case was originally filed and state court and then removed to federal court. 

4. Neff (CA) visits Oregon and is astonished to find a house on a parcel of land that Neff had purchased some years earlier from Mitchell (WA). After some investigation, Neff learns that the house was built and is currently occupied by Pennoyer (OR), who claims to have purchased the land from Mitchell. Neff brings a quiet title action in federal court against Pennoyer, seeking a declaratory judgment that Neff is the sole rightful owner of the property, which is valued at $100,000. Under state law, Pennoyer may, in the same action, assert his own claim (a "third-party claim") against Mitchell to recover $80,000 for breach of contract & fraud in the event the court decides the quiet title claim in favor of Neff. Under federal law, specifically Rule 14 of the Federal Rules of Civil Procedure, Pennoyer may not assert this type of third-party claim; instead he would have to bring a separate action against Mitchell following the outcome of the quiet title suit. Which law should the federal court apply to each issue? 
	a. State law, because it is in direct conflict with federal law. 
	b. FRCP Rule 14, if the court determines that it advances an important federal interest. 
	c. FRCP Rule 14, regardless of the rationale behind it. 
	d. Whichever the court determines is most equitable and efficient.  

The correct answer is C. The problem indicates that the federal rule at issue is part of the FRCP. Under _Hanna_, if there is a direct conflict between the FRCP and state law, then the federal court follows the FRCP rule as long as it "really regulates procedure", i.e. does not alter any substantive rights. There is a direct conflict here: state law would allow joinder of the third-party claim, but FRCP Rule 14 does not. This is a valid procedural rule under the REA. It doesn't affect Pennoyer's rights or Mitchell's liabilities; it merely requires that Pennoyer assert his claim against Mitchell in a separate action. 

Even under the _Erie-Byrd_ analysis (i.e. if the choice were between state law and a federal practice not governed by the FRCP), this would be regarded as a choice between state and federal procedures, not substantive rules of decision. Following the federal practice wouldn't alter Pennoyer's rights or Mitchell's liability for breach of contract or fraud (which would be defined under state law), and there is no reason to expect different outcomes merely because Pennoyer has to assert his claim against Mitchell in a separate action (as the federal rule requires) rather than in the same action as Neff's claim against Pennoyer (as the state rule would permit). Consequently, the "twin concerns of _Erie_", i.e. forum shopping to take advantage of more favorable decisional rules, and the resulting "inequitable administration of the laws", are not at stake here. 

5. In which of the following instances must a federal court apply state law, rather than federal law, in a diversity case)? 
	a. Under state law, a plaintiff seeking a preliminary injunction must prove _both_ that it will suffer irreparable harm if the injunction is denied _and_ that this harm outweighs any harm to the defendant if the injunction is granted. In federal court, the plaintiff has the burden of it will suffer irreparable harm if the injunction is denied; the defendant then has the burden of proving it will suffer greater harm if the injunction is granted. 
	b. Under state law, a plaintiff asserting a claim for breach of a written contract must attach a copy of the contract to the complaint. FRCP Rule 8 merely requires that the complaint contain "a short and plain statement of the claim"; production of the written contract happens during the discovery process under FRCP Rule 26 and 34. 
	c. Under state law, before a civil suit may proceed to trial, the parties must participate in a court-supervised mediation process. Under federal law, mediation is voluntary and requires the agreement of all parties. 
	d. All of the above. 

The correct answer is A. State law and federal law differ in how they allocate the burden of proof as between the plaintiff and defendant. This is the sort of difference that is regarded as "substantive" under Erie: it affects the rights and potential liabilities of the parties and is likely to result in different outcomes in otherwise identical cases. 

B is incorrect, because this rule is merely a matter of procedure: when must the plaintiff produce a copy of the document. The difference doesn't alter the substantive rules for determining whether there is a breach of contract. 

C is incorrect, because the mediation requirement is simply a procedure for aiding the parties in reaching a settlement. It doesn't affect their substantive rights or liabilities. Whether the parties first go through mediation or go directly to trial will not have any predicable or systematic effect on the outcome in the event the case does go to trial. 
