---

date: Fall 2019

title: Civil Procedure
subtitle: "Quiz 3: Pleadings, Joinder, & Summary Judgment"

author: Eric M. Fink
affiliation: Elon Law School 

exam: true

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.tex
    
---

# Instructions

- This is an open-book/notes quiz. You may use any printed material, but no computers or other electronic devices. 
- You have 30 minutes to complete the quiz. 
- When you are done, return the questions and your answer sheet to the proctor. 
- Include your Midterm Exam ID number, *not your name*, on your answer sheet.

# Note 

### For each question, assume that all claims are filed in federal court and that the court has personal jurisdiction over each party and subject matter jurisdiction over all claims. 

\newpage 

# Questions 

1. The Carbolic Smoke Bomb Co. sells a product that the company claims will prevent colds and flu. Carlil buys one of the company's smoke balls, uses it according to the directions, but nevertheless becomes ill with the flu. Carlil sues the company for fraud. The elements of Carlil's fraud claim are as follows: (1) The defendant made representations about the nature and quality of its product, knowing that those representations were false, (2) the defendant made those representations with the intent to induce purchases of its product, (3) the plaintiff bought the product in reliance on the false representations, and (4) the plaintiff suffered damages as a result of the false representations. Carlil's complaint includes these allegations:
 
	- Defendant manufactures and sells a product called the Carbolic Smoke Ball. Defendant's packaging and advertisements for the Carbolic Smoke Ball contain fraudulent claims about the nature and quality of the product. 
	 
	- Plaintiff purchased a Carbilic Smoke Ball and used it as directed, but became ill with the flu. As a result, she incurred damages including medical expenses and pain & suffering. 

	If the company files a motion to dismiss under FRCP Rule 12(b)(6), how should the court rule?

	a. Grant the motion, because it is implausible that Carlil would have believed the company's advertisements.
	
	b. Grant the motion, because Carlil has not provided sufficient detail in support of her claim.
	
	c. Deny the motion, because the complaint contains a short and plain statement of the grounds for relief.
	
	d. Deny the motion, because Carlil may be able to prove the elements of her claim at trial.

##### Questions 2 & 3 are based on the following facts: 

Pauline sues Darla in federal court in the state of Euphoria, asserting a claim for intentional infliction of emotional distress ("IIED"). Under Euphoria state law (which governs Pauline's claim), the elements of an IIED claim are: (1) the defendant engaged in extreme and outrageous conduct, (2) the defendant did so with the intent to cause the plaintiff severe emotional distress, and (3) the plaintiff suffered severe emotional distress as a result of the defendant's conduct. These are the relevant paragraph's of Pauline's complaint: 

- Plaintiff Pauline was engaged to be married to Harold Henderson. Shortly before their scheduled wedding, Henderson broke off the engagement, telling Plaintiff he was no longer in love with her and had fallen in love with Defendant Darla. 

- On information and belief, at various times before Henderson broke off the engagement, Defendant told Henderson lies about Plaintiff and pretended to be in love with Henderson, for the purpose of inducing Henderson to break off the engagement. 
 
- As a result of Defendant's actions, Plaintiff has suffered severe emotional distress. 

Wherefore, Plaintiff Pauline requests judgment against the Defendant in an amount greater than $75,000.

2. If Darla moves to dismiss the complaint under FRCP Rule 12(b)(6), on which of the following grounds is the court most likely to grant the motion? 

	a. Euphoria state law does not recognize claims for intentional infliction of emotional distress for a third-party's interference with an engagement. 
	b. The complaint does not explain in sufficient detail how Darla allegedly induced Harold to break off the engagement and what emotional distress Darla allegedly suffered. 
	c. The complaint does not adequately specify and establish the basis for the amount of damages sought. 
	d. None of the above. 

3. If Darla moves to for sanctions against Pauline and her attorney under Rule 11, on which of the following grounds is the court most likely to grant the motion? 

	a. The Euphoria Supreme Court (the state's highest court) has held that there is no claim under Euphoria law for intentional infliction of emotional distress for a third-party’s interference with an engagement.
	b. Pauline has no evidence that Darla said or did anything to prompt Harold's actions, and Pauline's attorney made no effort to investigate this before filing the complaint. 
	c. Pauline brought her suit to retaliate against Darla for embarassing Pauline at a party a few weeks before Harold broke off the engagement. 
	d. All of the above. 

4. In October 2013, Priscilla bought a set of cordless power tools manufactured by Drecker Tools, Inc. The set included a power drill, a circular saw, and a rotary sander, along with a charger and battery pack that fits each of the tools. In May 2019, while Priscilla was using the drill, the bit came loose and lodged in her eye. In July 2019, Priscilla sued Drecker for negligence. In her complaint, Priscilla alleged that the accident resulted from a defect in the drill's design and/or manufacture. In August 2019, Drecker filed and served its answer, admitting that it manufactured the drill but denying that there was any defect in the design or manufacture. 

	In September 2019, Priscilla's house was destroyed in a fire that started when the charger exploded while Priscilla was charging the battery pack. In November 2019, Priscilla moves for leave to amend her complaint. The proposed amended complaint asserts these new allegations & claims against Drecker: 

	- A design and/or manufacturing defect in the charger caused the explosion and fire that destroyed Priscilla's house. 
    - The instructions that came with the drill did not warn against using it without wearing eye protection, and Drecker's negligent failure to provide such a warning contributed to Priscilla's injury from the flying drill bit. 

  	Under the applicable state law, the statute of limitations for these claims is 6 years from the date of purchase of the product, which in this case ran out in October 2019. If Drecker opposes the motion, should the court grant leave to amend?

	a. No, because the amendment would be futile since the statute of limitations has run out for both new claims. 
	b. Yes, but only to add the design/manufacturing defect claim based on the charger explosion, because Priscilla knew or should have known about the lack of a warning against the using the drill without eye protection before she filed her original complaint. 
	c. Yes, but only to add the claim for negligent failure to warn based on the injury from the flying drill bit, because the claim based on the charge explosion is barred by the statute of limitations.
	d. Yes, for both claims. 

##### Questions 5 & 6 are based on the following facts: 

Andrea has a weekend house in the Pennsylvania countryside. Bart owns a goat farm adjacent to Andrea's vacation house. Bart's goats have repeatedly slipped through the gap and bathed in a creek that runs through Andrea's property, fouling the creek with their droppings. After this happens for the tenth time, an enraged Andrea shoots and kills the offending goat. Several days later, after searching in vain for his missing goat, Bart notices the animal's carcass next to the creek on Andrea's property. Bart rushes into Andrea's yard, accusing her of killing his goat. A fight ensures, in the course of which, Bart hits Andrea over the head with a shovel. 

5. Andrea sues Bart, asserting two claims: (1) battery, alleging that Bart intentionally hit her with the shovel, and (2) trespass, seeking damages for the cost of cleaning up the mess that Bart's goat left in the creek. Is joinder of these claims proper? 

	a. Yes, even if the claims arose from two distinct transactions or occurrences. 
	b. Yes, because there is a factual connection between the two incidents giving rise to the claims.  
	c. No, because the two claims are based on logically distinct conduct that occurred days apart. 
	d. No, because  a plaintiff may not combine tort and property claims in the same suit. 

6. Assume that Andrea asserts only the claim for battery based on her injuries from being hit with the shovel. In his answer, Bart denies intentionally hitting Andrea with the shovel and alleges that he did so accidentally while trying to wrest the shovel away from Andrea after she hit him with it. Bart also asserts two counterclaims: (1) a claim for battery, alleging that Andrea intentionally hit him with the shovel after he accused her of killing his goat (“Claim 1”), and (2) a claim for trespass to chattel, seeking damages for the loss of the goat (“Claim 2”). Which of the following is correct?

	a. Both claims are compulsory counterclaims. 
	b. Both claims are permissive counterclaims. 
	c. Claim 1 is a compulsory counterclaim, and Claim 2 is a permissive counterclaim.  
	d. Claim 1 is a compulsory counterclaim, and Claim 2 is not a proper counterclaim. 

\newpage 
   
7. Adele buys a new boat, and hires Belinda to transport it to Adele's lake house. While Belinda is en route, she is involved in a collision with Craig, who is driving a brand new Cadillac. Craig and Belinda both sustain serious injuries in the collision, and both of their vehicles, along with the boat, are totaled. 

	Adele sues Craig for the damage to her boat, which she alleges was caused by Craig's negligence. Craig denies that he was negligent, and alleges that the accident was caused by Belinda's negligence. Which of the following is true? 

	I) Craig may join Belinda as a third party defendant, asserting claims against Belinda for his personal injuries and the damage to his car. 

	II) Craig may assert a counterclaim against Adele, alleging that Adele is vicarioualy liable for Belinda's negligence because Belinda was acting as Adele's agent in transporting the boat.
	
	III) If Craig asserts a counterclaim against Adele seeking to hold her vicariously liable for Belinda's negligence, he may join Belinda as a co-defendant seeking to hold her liable for her own negligence. 
	
	a. I, II, & III
	b. I & II 
	c. II & III 
	d. II only 
		    
8. Anton sues Beverly for breach of contract. Anton also has a claim against Claire, Beverly's spouse, for defamation. Anton wants to sue Beverly & Claire together in the same suit. Would joinder of Beverly & Claire as co-defendants in the same action be proper?

	a. Yes, because as a married couple Beverly & Claire have common interests in any claims in which they are parties. 
	b. Yes, if the court concludes that the interests of judicial economy and convenience to the parties would be served by deciding the claims together. 
	c. No, if the claims against Beverly & Claire arise from different transactions and occurrences.
	d. No, because a plaintiff may not join co-defendants where the plaintiff asserts a contract claim against one defendant and a tort claim against the other defendant.

\newpage 

9. Gene sues Employer, alleging that he was fired in violation of the terms of his employment contract. Employer moves for summary judgment, supporting the motion with affidavits, deposition testimony, and documentary evidence that Employer contends show there is no genuine dispute of material fact surrounding the circumstances of Gene's firing, and that Employer is entitled to judgment in his favor as a matter of law because the facts do not establish any contractual breach. What must Gene do to avoid summary judgment in favor of Employer?
 
	a. Produce evidence in admissible form showing the existence of a genuine issue of material fact regarding the discharge.
	b. Point to the parts of Gene's pleadings that allege a breach of contract. 
	c. Show that evidence already in the record supports a reasonable inference in Gene's favor. 
	d. Show that evidence already in the record, or additional evidence provided in response to the summary judgment motion, would, if offered in admissible form at trial, support a reasonable inference in Gene's favor.

10. Pam hires Deb to install a ceiling fan in her home. A few weeks after Deb completes the job, the ceiling fan comes loose and falls down, hitting and injuring Pam, who was unlucky enough to be standing underneath it at the time. Pam sues Deb in federal court for negligence in the installation of the fan. After the parties have conducted discovery, Deb moves for summary judgment, supporting the motion with an affidavit from an expert engineer who examines the fan and ceiling and opines that the fan was correctly installed, but that the ceiling material was weaked as a result of internal decay not visible to Deb at the time she installed the fan. Pam responds, opposing Deb's motion for summary judgment and seeking summary judgment in Pam's favor. In support, Pam offers an affidavit from her own expert who examined the ceiling and found no decay, and concludes that the fan had merely been attached to the sheet rock, not to a ceiling beam as would have been appropriate given the weight of the fan. Pam's expert further opines that, had there been decay sufficient to weaken the ceiling, a competent fan installer would have identified it. How should the court rule?

	a. Grant Pam's motion, if the court determines that her expert is more credible. 
	b. Grant Deb's motion, if the court determines that her expert is more credible. 
	c. Deny both motions, because neither has adequate evidentiary support. 
	d. Deny both motions, because there is a genuine issue of material fact.

