---
subject: Civil Procedure
author: Professor Fink
title: FRCP & Statutes for Final Exam

format:
  pdf:
    template: rules_template.tex
    keep-tex: true
    output-file: CivProRulesHandout

---

## I. Federal Rules of Civil Procedure 

### Rule 8. General Rules of Pleading

(a) Claim for Relief. A pleading that states a claim for relief must contain:
	(1) a short and plain statement of the grounds for the court’s jurisdiction, unless the court already has jurisdiction and the claim needs no new jurisdictional support;
	(2) a short and plain statement of the claim showing that the pleader is entitled to relief; and
	(3) a demand for the relief sought, which may include relief in the alternative or different types of relief. 
(b) Defenses; Admissions and Denials.
	(1) In General. In responding to a pleading, a party must:
		(A) state in short and plain terms its defenses to each claim asserted against it; and
		(B) admit or deny the allegations asserted against it by an opposing party. 
	(2) Denials—Responding to the Substance. A denial must fairly respond to the substance of the allegation. 
	(3) General and Specific Denials. A party that intends in good faith to deny all the allegations of a pleading—including the jurisdictional grounds—may do so by a general denial. A party that does not intend to deny all the allegations must either specifically deny designated allegations or generally deny all except those specifically admitted. 
	(4) Denying Part of an Allegation. A party that intends in good faith to deny only part of an allegation must admit the part that is true and deny the rest. 
	(5) Lacking Knowledge or Information. A party that lacks knowledge or information sufficient to form a belief about the truth of an allegation must so state, and the statement has the effect of a denial. 
	(6) Effect of Failing to Deny. An allegation—other than one relating to the amount of damages—is admitted if a responsive pleading is required and the allegation is not denied. If a responsive pleading is not required, an allegation is considered denied or avoided. 
(c) Affirmative Defenses. 
	(1) In General. In responding to a pleading, a party must affirmatively state any avoidance or affirmative defense, including:
		- accord and satisfaction;
		- arbitration and award;
		- assumption of risk;
		- duress;
		- contributory negligence;
		- estoppel;
		- failure of consideration;
		- fraud;
		- illegality;
		- injury by fellow servant;
		- laches;
		- license;
		- payment;
		- release;
		- res judicata;
		- statute of frauds;
		- statute of limitations; and
		- waiver. 

### Rule 9. Pleading Special Matters

(b) Fraud or Mistake; Conditions of Mind. In alleging fraud or mistake, a party must state with particularity the circumstances constituting fraud or mistake. Malice, intent, knowledge, and other conditions of a person’s mind may be alleged generally. 

### Rule 11. Signing Pleadings, Motions, and Other Papers; Representations to the Court; Sanctions

(a) Signature. Every pleading, written motion, and other paper must be signed by at least one attorney of record in the attorney’s name—or by a party personally if the party is unrepresented. The paper must state the signer’s address, e-mail address, and telephone number. Unless a Rule or statute specifically states otherwise, a pleading need not be verified or accompanied by an affidavit. The court must strike an unsigned paper unless the omission is promptly corrected after being called to the attorney’s or party’s attention. 
(b) Representations to the Court. By presenting to the court a pleading, written motion, or other paper—whether by signing, filing, submitting, or later advocating it—an attorney or unrepresented party certifies that to the best of the person’s knowledge, information, and belief, formed after an inquiry reasonable under the circumstances:
	(1) it is not being presented for any improper purpose, such as to harass, cause unnecessary delay, or needlessly increase the cost of litigation;
	(2) the claims, defenses, and other legal contentions are warranted by existing law or by a nonfrivolous argument for extending, modifying, or reversing existing law or for establishing new law;
	(3) the factual contentions have evidentiary support or, if specifically so identified, will likely have evidentiary support after a reasonable opportunity for further investigation or discovery; and
	(4) the denials of factual contentions are warranted on the evidence or, if specifically so identified, are reasonably based on belief or a lack of information. 

### Rule 12. Defenses and Objections: When and How Presented; Motion for Judgment on the Pleadings; Consolidating Motions; Waiving Defenses; Pretrial Hearing

(b) How to Present Defenses. Every defense to a claim for relief in any pleading must be asserted in the responsive pleading if one is required. But a party may assert the following defenses by motion:
	(1) lack of subject-matter jurisdiction;
	(2) lack of personal jurisdiction;
	(3) improper venue;
	(4) insufficient process;
	(5) insufficient service of process;
	(6) failure to state a claim upon which relief can be granted; and
	(7) failure to join a party under Rule 19. 

### Rule 13. Counterclaim and Crossclaim

(a) Compulsory Counterclaim. 
	(1) In General. A pleading must state as a counterclaim any claim that—at the time of its service—the pleader has against an opposing party if the claim:
		(A) arises out of the transaction or occurrence that is the subject matter of the opposing party’s claim; and
		(B) does not require adding another party over whom the court cannot acquire jurisdiction. 
(b) Permissive Counterclaim. A pleading may state as a counterclaim against an opposing party any claim that is not compulsory. 
(g) Crossclaim Against a Coparty. A pleading may state as a crossclaim any claim by one party against a coparty if the claim arises out of the transaction or occurrence that is the subject matter of the original action or of a counterclaim, or if the claim relates to any property that is the subject matter of the original action. The crossclaim may include a claim that the coparty is or may be liable to the cross-claimant for all or part of a claim asserted in the action against the cross-claimant. 
(h) Joining Additional Parties. Rules 19 and 20 govern the addition of a person as a party to a counterclaim or crossclaim. 

### Rule 14. Third-Party Practice

(a) When a Defending Party May Bring in a Third Party. 
	(1) Timing of the Summons and Complaint. A defending party may, as third-party plaintiff, serve a summons and complaint on a nonparty who is or may be liable to it for all or part of the claim against it. But the third-party plaintiff must, by motion, obtain the court’s leave if it files the third-party complaint more than 14 days after serving its original answer. 
	(2) Third-Party Defendant’s Claims and Defenses. The person served with the summons and third-party complaint—the “third-party defendant”:
		(A) must assert any defense against the third-party plaintiff’s claim under Rule 12;
		(B) must assert any counterclaim against the third-party plaintiff under Rule 13(a), and may assert any counterclaim against the third-party plaintiff under Rule 13(b) or any crossclaim against another third-party defendant under Rule 13(g);
		(C) may assert against the plaintiff any defense that the third-party plaintiff has to the plaintiff’s claim; and
		(D) may also assert against the plaintiff any claim arising out of the transaction or occurrence that is the subject matter of the plaintiff’s claim against the third-party plaintiff. 
	(3) Plaintiff’s Claims Against a Third-Party Defendant. The plaintiff may assert against the third-party defendant any claim arising out of the transaction or occurrence that is the subject matter of the plaintiff’s claim against the third-party plaintiff. The third-party defendant must then assert any defense under Rule 12 and any counterclaim under Rule 13(a), and may assert any counterclaim under Rule 13(b) or any crossclaim under Rule 13(g). 

### Rule 15. Amended and Supplemental Pleadings

(a) Amendments Before Trial. 
	(1) Amending as a Matter of Course. A party may amend its pleading once as a matter of course within:
		(A) 21 days after serving it, or 
		(B) if the pleading is one to which a responsive pleading is required, 21 days after service of a responsive pleading or 21 days after service of a motion under Rule 12(b), (e), or (f), whichever is earlier.
	(2) Other Amendments. In all other cases, a party may amend its pleading only with the opposing party’s written consent or the court’s leave. The court should freely give leave when justice so requires. 
(b) \[omitted\]
(c) Relation Back of Amendments. 
	(1) When an Amendment Relates Back. An amendment to a pleading relates back to the date of the original pleading when:
		(A) the law that provides the applicable statute of limitations allows relation back;
		(B) the amendment asserts a claim or defense that arose out of the conduct, transaction, or occurrence set out—or attempted to be set out—in the original pleading; or
		(C) the amendment changes the party or the naming of the party against whom a claim is asserted, if Rule 15(c)(1)(B) is satisfied and if, within the period provided by Rule 4(m) for serving the summons and complaint, the party to be brought in by amendment:
			(i) received such notice of the action that it will not be prejudiced in defending on the merits; and
			(ii) knew or should have known that the action would have been brought against it, but for a mistake concerning the proper party’s identity. 

### Rule 18. Joinder of Claims

(a) In General. A party asserting a claim, counterclaim, crossclaim, or third-party claim may join, as independent or alternative claims, as many claims as it has against an opposing party. 

### Rule 19. Required Joinder of Parties

(a) Persons Required to Be Joined if Feasible. 
	(1) Required Party. A person who is subject to service of process and whose joinder will not deprive the court of subject-matter jurisdiction must be joined as a party if:
		(A) in that person’s absence, the court cannot accord complete relief among existing parties; or
		(B) that person claims an interest relating to the subject of the action and is so situated that disposing of the action in the person’s absence may:
			(i) as a practical matter impair or impede the person’s ability to protect the interest; or
			(ii) leave an existing party subject to a substantial risk of incurring double, multiple, or otherwise inconsistent obligations because of the interest. 
(b) When Joinder Is Not Feasible. If a person who is required to be joined if feasible cannot be joined, the court must determine whether, in equity and good conscience, the action should proceed among the existing parties or should be dismissed. The factors for the court to consider include:
	(1) the extent to which a judgment rendered in the person’s absence might prejudice that person or the existing parties;
	(2) the extent to which any prejudice could be lessened or avoided by:
		(A) protective provisions in the judgment;
		(B) shaping the relief; or
		(C) other measures;
	(3) whether a judgment rendered in the person’s absence would be adequate; and
	(4) whether the plaintiff would have an adequate remedy if the action were dismissed for nonjoinder. 

### Rule 20. Permissive Joinder of Parties

(a) Persons Who May Join or Be Joined. 
	(1) Plaintiffs. Persons may join in one action as plaintiffs if:
		(A) they assert any right to relief jointly, severally, or in the alternative with respect to or arising out of the same transaction, occurrence, or series of transactions or occurrences; and
		(B) any question of law or fact common to all plaintiffs will arise in the action. 
	(2) Defendants. Persons—as well as a vessel, cargo, or other property subject to admiralty process in rem—may be joined in one action as defendants if:
		(A) any right to relief is asserted against them jointly, severally, or in the alternative with respect to or arising out of the same transaction, occurrence, or series of transactions or occurrences; and
		(B) any question of law or fact common to all defendants will arise in the action. 

### Rule 56. Summary Judgment

(a) Motion for Summary Judgment or Partial Summary Judgment. A party may move for summary judgment, identifying each claim or defense — or the part of each claim or defense — on which summary judgment is sought. The court shall grant summary judgment if the movant shows that there is no genuine dispute as to any material fact and the movant is entitled to judgment as a matter of law. The court should state on the record the reasons for granting or denying the motion.
(b) \[omitted\]
(c) Procedures.
	(1) Supporting Factual Positions. A party asserting that a fact cannot be or is genuinely disputed must support the assertion by:
		(A) citing to particular parts of materials in the record, including depositions, documents, electronically stored information, affidavits or declarations, stipulations (including those made for purposes of the motion only), admissions, interrogatory answers, or other materials; or
		(B) showing that the materials cited do not establish the absence or presence of a genuine dispute, or that an adverse party cannot produce admissible evidence to support the fact.
	(2) _Objection That a Fact Is Not Supported by Admissible Evidence._ A party may object that the material cited to support or dispute a fact cannot be presented in a form that would be admissible in evidence.
	(3) _Materials Not Cited._ The court need consider only the cited materials, but it may consider other materials in the record.
	(4) _Affidavits or Declarations._ An affidavit or declaration used to support or oppose a motion must be made on personal knowledge, set out facts that would be admissible in evidence, and show that the affiant or declarant is competent to testify on the matters stated.
(d) \[omitted\]
(e) Failing to Properly Support or Address a Fact. If a party fails to properly support an assertion of fact or fails to properly address another party’s assertion of fact as required by Rule 56(c), the court may:
	(1) give an opportunity to properly support or address the fact;
	(2) consider the fact undisputed for purposes of the motion;
	(3) grant summary judgment if the motion and supporting materials — including the facts considered undisputed — show that the movant is entitled to it; or
	(4) issue any other appropriate order.

\newpage

## II. Federal Statutes 

### 28 U.S.C. § 1331. Federal question

The district courts shall have original jurisdiction of all civil actions arising under the Constitution, laws, or treaties of the United States. 

### 28 U.S.C. § 1332. Diversity of citizenship; amount in controversy; costs

(a) The district courts shall have original jurisdiction of all civil actions where the matter in controversy exceeds the sum or value of $75,000, exclusive of interest and costs, and is between—
	(1) citizens of different States;
(b) \[Omitted\]
(c) For the purposes of this section and section 1441 of this title—
	(1) a corporation shall be deemed to be a citizen of every State and foreign state by which it has been incorporated and of the State or foreign state where it has its principal place of business [ ...]
	(2) the legal representative of the estate of a decedent shall be deemed to be a citizen only of the same State as the decedent, and the legal representative of an infant or incompetent shall be deemed to be a citizen only of the same State as the infant or incompetent.

### 28 U.S.C. § 1367. Supplemental jurisdiction

(a) Except as provided in subsections (b) and (c) or as expressly provided otherwise by Federal statute, in any civil action of which the district courts have original jurisdiction, the district courts shall have supplemental jurisdiction over all other claims that are so related to claims in the action within such original jurisdiction that they form part of the same case or controversy under Article III of the United States Constitution. Such supplemental jurisdiction shall include claims that involve the joinder or intervention of additional parties. 
(b) In any civil action of which the district courts have original jurisdiction founded solely on section 1332 of this title, the district courts shall not have supplemental jurisdiction under subsection (a) over claims by plaintiffs against persons made parties under Rule 14, 19, 20, or 24 of the Federal Rules of Civil Procedure, or over claims by persons proposed to be joined as plaintiffs under Rule 19 of such rules, or seeking to intervene as plaintiffs under Rule 24 of such rules, when exercising supplemental jurisdiction over such claims would be inconsistent with the jurisdictional requirements of section 1332.  

### 28 U.S.C. § 1441. Removal of civil actions

(a) Generally.— Except as otherwise expressly provided by Act of Congress, any civil action brought in a State court of which the district courts of the United States have original jurisdiction, may be removed by the defendant or the defendants, to the district court of the United States for the district and division embracing the place where such action is pending.
(b) Removal Based on Diversity of Citizenship.—
    (1) In determining whether a civil action is removable on the basis of the jurisdiction under section 1332(a) of this title, the citizenship of defendants sued under fictitious names shall be disregarded.
    (2) A civil action otherwise removable solely on the basis of the jurisdiction under section 1332(a) of this title may not be removed if any of the parties in interest properly joined and served as defendants is a citizen of the State in which such action is brought.