# Description

This course surveys federal and state laws governing employment, in both the individual and organized labor settings. Topics to be covered include establishing an employment relationship; recruitment & hiring; the scope and limits of supervisory control; confidentiality & competition; wages & hours; employee health & safety; and termination of employment. 

After completing the course, you should be able to recognize and diagnose legal issues arising in the employment context, analyze those issues under the applicable law, and help clients avoid legal problems or pursue remedies when they arise. Simulation problems, including in-class discussion and take-home assignments, provide an opportunity to develop practical skills for representing clients in employment matters.

# Course Materials

## Required

Employment Law: An Open-Source Casebook (version 4.1, December 2025). Available on the course website: [emfink.net/EmploymentLaw](http://www.emfink.net/EmploymentLaw).  

Rachel Arnow-Richman & Nantiya Ruan, Developing Professional Skills: Workplace Law (West Academic 2017) ("Workbook"). 

## Suggested

Richard A. Bales, Jeffrey M. Hirsch, & Paul M. Secunda, Understanding Employment Law (4th. ed. Carolina Academic Press 2025)

# Policies

## Grading

Your final grade for this course will be based on two take-home problem assignments (35% each) and participation in class discussions (30%). There will be no final exam.

- The take-home assignments will be based on problems from the _Developing Professional Skills_ workbook. I will provide further instructions for these assignments in class. You should submit each assignment to my faculty assistant, Jasmin Whitsett by email (jwhitsett4@elon.edu) no later than 10:00am on the due date (see _Schedule & Assignments_ below). **Be sure to include your Exam ID number, _not your name_, at the top of your submission.**

- The use of generative AI for take-home assignments is not permitted. The purpose of the assignments is to give you an opportunity to demonstrate what you have learned and what you can do. Among the many reasons to avoid artificial intelligence,[^syllabusAI] the most compelling is that it demeans your own intelligence.

- The class participation component of your grade will be based on your constructive engagement in class discussions and in-class problem exercises. This will include presenting at least one question about the assigned reading for at least one class each week (beginning with the second week of class, i.e. Jan. 12 & 14). I will provide further guidance on this assignment in class. You should send your questions to me by email before the class for which the reading is assigned.

- Consistent with ABA Standard 310,[^syllabusABA] Elon Law School policy[^syllabusStudentHandbook] requires that "Each credit hour of in-class instructional time must also require at least two additional hours of out-of-class student work." Completion of the assigned reading for each class, the preparation of discussion questions, and the two take-home problems will satisfy this requirement.

## Attendance

Elon Law School has adopted the following attendance policy for all courses:

> The Law School administers a policy that a student maintain regular and punctual class attendance in all courses in which the student is registered, including externships, clinical courses, or simulation courses. Faculty members will give students written notice of their attendance policies before or during the first week of class. These policies may include, but are not limited to: treating late arrivals, early departures, and/or lack of preparation as absences  imposing grade or point reductions for absences, including assigning a failing grade or involuntarily withdrawing a student from the class  and any other policies that a professor deems appropriate to create a rigorous and professional classroom environment.
>  
> In case of illness or emergency, students may contact the Office of Student and Professional Life, which will then notify the student’s instructors. A student may notify the faculty member directly of a planned absence and should refer to individual faculty members regarding any policy that may apply. In the case of prolonged illness or incapacity, the student should contact the [Office of Student Life](https://www.elon.edu/u/law/students/).

You should let me know (in advance if feasible) if you are unable to attend class, will arrive late, or must leave early. I do not require an explanation of the reason, nor do I require a doctor's note or other documentation.

## Disability Accommodations

For disability accommodation requests, contact the [Office of Academic Accommodations and Accessibility](https://www.elon.edu/u/law/students/student-resources/academic-accommodations-accessibility/).

## Honor Code

The Law School [honor code](https://www.elon.edu/u/law/students/honor-code/) applies to all activities related to your law school study, including class meetings, assignments, and examinations.

# Schedule & Assignments

(_Note:_ This class will not meet on Monday, January 19th)

### 1\. Foundations of Employment Law

#### January 5 & 7

- Employment as a Socio-Legal Relationship, _Casebook_ Chap. 1

#### January 12

- Labor Organizing & Concerted Activity, _Casebook_ Chap. 2

### 2\. Establishing an Employment Relationship

#### January 14 & 21

- Identifying Employees, _Casebook_ Chap. 3, § 1

#### January 26 

- Identifying Employers, _Casebook_ Chap. 3, § 2

#### January 28 

- Recruitment & Hiring, _Casebook_ Chap. 3, § 3

### 3\. Scope & Limits of Employer Control

#### February 2

- Control At Work, _Casebook_ Chap. 4, § 1
- _Problem Assignment 1:_ Sexual Harassment (Workbook, Chap. 7)

#### February 4 

- Control Outside Work, _Casebook_ Chap. 4, § 2

### 4\. Employee Duties to Employers

#### February 9 

- Confidentiality, _Casebook_ Chap. 5, § 1

#### February 11

- Loyalty, _Casebook_ Chap. 5, § 2

### 5\. Wages & Hours

#### February 16 & 18

- Minimum Wage, Overtime, & Wage Payments, _Casebook_ Chap. 6

### 6\. Employee Health & Safety

#### February 23

- Workers' Compensation & OSHA, _Casebook_ Chap. 7, § 1

#### February 25

- FMLA & ADA, _Casebook_ Chap. 7, § 2

### 7\. Terminating Employment

#### March 2

- Express "Good Cause" Requirements & Implied Contract Limits, _Casebook_ Chap. 8, §§ 1.1 & 1.2

#### March 4

- Tort Claims & Statutory Protections, _Casebook_ Chap. 8, §§ 1.3 & 1.4
- _Problem Assignment 2:_ Whistleblowers (Workbook, Chap. 4)

#### March 9

- Unemployment Compensation, _Casebook_ Chap. 8, § 2

#### March 11

- Make-up class (if needed)

[^syllabusAI]: It is an unreliable tool for legal research, as attorneys continue to learn the hard way. _See, e.g._, @WithersCityAberdeen_NDMiss2026; @MillerRegionsBank_NDAla2026; @MezuMezu_MdAppCt2025; @NolandLandFreeLP_CalCtApp2025; @GarnerKadinceInc_UtahCtApp2025. It consumes "a staggering amount of electricity" and water, imposing significant social and environmental costs. @Zewe_MITNews2025; @AIhasenvironmental2025; @Crawford2024. It makes you stupid. @Kosmyna_MITMediaLab2025. Its "current design and massive scaled deployment" corrodes "the institutions that support modern democratic life". @Hartzog2026.

[^syllabusABA]: See [2025-2026 Standards and Rules of Procedure for Approval of Law Schools](https://www.americanbar.org/content/dam/aba/administrative/legal_education_and_admissions_to_the_bar/standards/2025-2026/2025-2026-standards-chapter-3.pdf), Standard 310. 

[^syllabusStudentHandbook]: See [2025-26 Student Handbook](https://eloncdn.blob.core.windows.net/eu3/sites/996/2020/01/GSO-Student-Handbook-2025-26.pdf), Appendix A.